version: 0.2
phases:
  build:
    commands:
    - mvn test
  post_build:
    commands:
    - mvn package
    - aws cloudformation package --template-file MyAppBuild::template.yaml --s3-bucket bark-bot --output-template-file outputTemplate.yaml
artifacts:
  type: zip
  files:
  - target/bark-bot-1.0-SNAPSHOT.jar
  - template.yaml
  - outputTemplate.yaml