version: 0.2
phases:
  build:
    commands:
    - mvn package
  post_build:
    commands:
    - aws cloudformation package
      --template-file template.yaml
      --s3-bucket bark-bot
      --output-template-file outputTemplate.yaml
artifacts:
  files:
  - target/bark-bot-1.0-SNAPSHOT.jar
  - template.yaml
  - outputTemplate.yaml