version: 0.2
phases:
  install:
    commands:
    - mvn install
  build:
    commands:
    - mvn package
  post_build:
    commands:
    - aws cloudformation package
      --template-file template.yaml
      --s3-bucket bark-bot
      --output-template-file outputTemplate.yaml
artifacts:
  files:
  - outputTemplate.yaml
  cache:
  - /root/.m2/**/*