AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Barks at bad boys
Resources:
  BarkBot:
    Type: AWS::Serverless::Function
    Properties:
      Handler: barkbot.Launcher::handleRequest
      Runtime: java8
      CodeUri: target/bark-bot-1.0-SNAPSHOT.jar
      FunctionName: BarkBot
      Description: Handles new messages
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          MAX_LABELS: 10
          MIN_CONFIDENCE: 50
          RETRY_TIMEOUT: 1000
          SECRET: AQICAHjrsPX5p9oTVDeV3RAt/8lmdGo73kyFBtH34y0u+LvvEgH+ZNvr2uorpX98sGHo8iseAAAAeDB2BgkqhkiG9w0BBwagaTBnAgEAMGIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBwSqhqezhlax6BOdAgEQgDXXht3ANeveh9wayw5rARaVDoWLE5SnTZXz+JzvYlhwkao+Ece/K2z3S7v0GC0IY5cGNbTyHA==
      Events:
        GroupMeCallBack:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Policies:
      - AmazonRekognitionFullAccess