AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Barks at bad boys!
Parameters:
  DimensionName:
    Type: String
    Description: Identifies the dimension being created.
  BotId:
    Type: String
    Description: Identifies the GroupMe bot being called.
Resources:
  BarkBotLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: barkbot.BarkBotLauncher::handleRequest
      Runtime: java8
      CodeUri: target/bark-bot-1.0-SNAPSHOT.jar
      FunctionName: !Sub BarkBotLambda${DimensionName}
      Description: Handles new messages.
      MemorySize: 256
      Timeout: 30
      Policies:
      - AmazonRekognitionFullAccess
      - AmazonS3FullAccess
      Environment:
        Variables:
          MAX_LABELS: 10
          MIN_CONFIDENCE: 50
          RETRY_TIMEOUT: 1000
          BOT_ID: !Ref BotId
          NOTIFIED_NAME: Protector Of Dogs
          NOTIFIED_USER_ID: 19893666
          MESSAGE_BUCKET: not-dog-pictures
          SOURCE: !Ref DimensionName
      Events:
        GroupMeCallback:
          Type: Api
          Properties:
            Path: /bark-bot
            Method: POST
            RestApiId: !Ref GroupMeCallback
  GroupMeCallback:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub BarkBotAPI${DimensionName}
      StageName: prod
      DefinitionBody:
        swagger: 2.0
        info:
          version: 1.0
          title: !Sub BarkBotAPI${DimensionName}
        paths:
          /bark-bot:
            post:
              summary: Hooks GroupMe up to API Gateway.
              produces:
              - application/json
              x-amazon-apigateway-integration:
                uri: !Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/*/functions/${BarkBotLambda.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
      MethodSettings:
        HttpMethod: POST
        LoggingLevel: ERROR
        MetricsEnabled: true
        ResourcePath: /
        ThrottlingBurstLimit: 5
        ThrottlingRateLimit: 5
      EndpointConfiguration: EDGE