AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Barks at bad boys!
Resources:
  BarkBotBeta:
    Type: AWS::Serverless::Function
    Properties:
      Handler: barkbot.Launcher::handleRequest
      Runtime: java8
      CodeUri: target/bark-bot-1.0-SNAPSHOT.jar
      FunctionName: BarkBotBeta
      Description: Handles new messages.
      MemorySize: 256
      Timeout: 30
      Policies:
      - AmazonRekognitionFullAccess
      - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          MAX_LABELS: 20
          MIN_CONFIDENCE: 25
          RETRY_TIMEOUT: 1000
          BUCKET_NAME: bot-id
          KEY: BarkBotBeta.txt
          NOTIFIED_NAME: Protector Of Dogs
          NOTIFIED_USER_ID: 19893666
      Events:
        GroupMeCallBack:
          Type: Api
          Properties:
            Path: /
            Method: POST