AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Barks at bad boys!
Parameters:
  BotIdAlpha:
    Type: String
    Description: Identifies GroupMe bot in alpha being called.
  BotIdBeta:
    Type: String
    Description: Identifies GroupMe bot in beta being called.
  BotIdProd:
    Type: String
    Description: Identifies GroupMe bot in prod being called.
Resources:
  BarkBotAlpha:
    Type: AWS::Serverless::Function
    Properties:
      Handler: barkbot.BarkBotLauncher::handleRequest
      Runtime: java8
      CodeUri: target/bark-bot-1.0-SNAPSHOT.jar
      FunctionName: BarkBotAlpha
      Description: Handles new messages.
      MemorySize: 256
      Timeout: 30
      Policies:
      - AmazonRekognitionFullAccess
      - AmazonS3FullAccess
      Environment:
        Variables:
          MAX_LABELS: 10
          MIN_CONFIDENCE: 50
          RETRY_TIMEOUT: 1000
          BOT_ID: !Ref BotIdAlpha
          NOTIFIED_NAME: Protector Of Dogs
          NOTIFIED_USER_ID: 19893666
          MESSAGE_BUCKET: not-dog-pictures
          SOURCE: !Ref BarkBotAlpha
      Events:
        GroupMeCallback:
          Type: Api
          Properties:
            Path: /bark-bot-alpha
            Method: POST
            RestApiId: !Ref BarkBotApi
  BarkBotBeta:
    Type: AWS::Serverless::Function
    Properties:
      Handler: barkbot.BarkBotLauncher::handleRequest
      Runtime: java8
      CodeUri: target/bark-bot-1.0-SNAPSHOT.jar
      FunctionName: BarkBotBeta
      Description: Handles new messages.
      MemorySize: 256
      Timeout: 30
      Policies:
      - AmazonRekognitionFullAccess
      - AmazonS3FullAccess
      Environment:
        Variables:
          MAX_LABELS: 10
          MIN_CONFIDENCE: 50
          RETRY_TIMEOUT: 1000
          BOT_ID: !Ref BotIdBeta
          NOTIFIED_NAME: Protector Of Dogs
          NOTIFIED_USER_ID: 19893666
          MESSAGE_BUCKET: not-dog-pictures
          SOURCE: !Ref BarkBotBeta
      Events:
        GroupMeCallback:
          Type: Api
          Properties:
            Path: /bark-bot-beta
            Method: POST
            RestApiId: !Ref BarkBotApi
  BarkBotProd:
    Type: AWS::Serverless::Function
    Properties:
      Handler: barkbot.BarkBotLauncher::handleRequest
      Runtime: java8
      CodeUri: target/bark-bot-1.0-SNAPSHOT.jar
      FunctionName: BarkBotProd
      Description: Handles new messages.
      MemorySize: 256
      Timeout: 30
      Policies:
      - AmazonRekognitionFullAccess
      - AmazonS3FullAccess
      Environment:
        Variables:
          MAX_LABELS: 10
          MIN_CONFIDENCE: 50
          RETRY_TIMEOUT: 1000
          BOT_ID: !Ref BotIdProd
          NOTIFIED_NAME: Protector Of Dogs
          NOTIFIED_USER_ID: 19893666
          MESSAGE_BUCKET: not-dog-pictures
          SOURCE: !Ref BarkBotProd
      Events:
        GroupMeCallback:
          Type: Api
          Properties:
            Path: /bark-bot-prod
            Method: POST
            RestApiId: !Ref BarkBotApi
  BarkBotApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: BarkBotApi
      StageName: PROD
      DefintionBody:
        swagger: 2.0
        info:
          title: Bark Bot Api
          description: Accepts callbacks from GroupMe.
        paths:
          /:
      MethodSettings:
        DataTraceEnabled: true
        HttpMethod: POST
        LoggingLevel: ERROR
        MetricsEnabled: true
        ResourcePath: /
        ThrottlingBurstLimit: 10
        ThrottlingRateLimit: 5
      EndpointConfiguration: EDGE
Outputs:
  BaseCallbackUrl:
    Description: Base callback URL without resource path.
    Value: !Sub "https://${BarkBotApi}.execute-api.${AWS::Region}.amazonaws.com/${BarkBotApi.StageName}/"